### ISSUE TITLE
[PD] Reflect on your development so far

### ISSUE THREAD

**Issue by zohrehKazemianpour** [zohrehKazemianpour/My-Coursework-Planner#78]
### Coursework content

You have now learned many new things: tools, skills, and programming language. Considering this, reflect on your development.

### Estimated time in hours

0.5

### What is the purpose of this assignment?

Reflect and celebrate how much you have developed your knowledge so far.

### How to submit

1. Think about 1 achievement you had and 1 professional skill (not technical skill) you still want to develop.
2. Write a paragraph about these two: **what** are they AND **why** do you think you did well OR still have to learn them?
4. Share this with your class on the thread about this coursework. If the thread doesn't exist yet, you are the first and can create it
5. Read your fellow trainees' messages and react to them with emojis that support them or are relevant to their content.
6. Copy the link to the Slack message you posted on this ticket
7. Copy a screenshot of the message you posted on this ticket

**Comment by zohrehKazemianpour** [comment]
Initially, I was not familiar with Google Sheets and SQL at all, but I took an online course taught by Google so I could learn it. After some time, I was then able to write SQL queries myself in Google Sheets and work on tasks myself. I still have difficulties finishing and focusing on outstanding tasks. Sometimes I get distressed when I’m not able to finish a task according to my plan.

**Comment by IsabelCudby** [comment]
Perfect english, no grammatical errors , no use of AI, only uploaded one point however the brief asked for two, so to improve you could expand on your work
